test8

diff --git a/.github/workflows/NaTiBack.yml b/.github/workflows/NaTiBack.yml
--- a/.github/workflows/NaTiBack.yml
+++ b/.github/workflows/NaTiBack.yml
@@ -84,29 +84,22 @@ jobs:
 
   # deploy_local job을 auto_merge_build_deploy 이후에 실행
   deploy_local:
-    runs-on: self-hosted
-    needs: auto_merge_build_deploy
-    if: needs.auto_merge_build_deploy.outputs.has_new_commits == 'true'
-    steps:
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+  runs-on: self-hosted
+  needs: auto_merge_build_deploy
+  if: needs.auto_merge_build_deploy.outputs.has_new_commits == 'true'
+  steps:
+    - name: Log in to Docker Hub
+      uses: docker/login-action@v2
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Pull Docker image from Docker Hub and run container
-        shell: pwsh
-        run: |
-          $stopContainer = docker stop yaggugifrontapp 2>$null
-          if (-not $?) {
-              Write-Host "Container not running or already stopped"
-          }
+    - name: Pull Docker image from Docker Hub and run container
+      run: |
+        docker stop yaggugifrontapp 2>/dev/null || echo "Container not running or already stopped"
 
-          $removeContainer = docker rm yaggugifrontapp 2>$null
-          if (-not $?) {
-              Write-Host "Container not found or already removed"
-          }
+        docker rm yaggugifrontapp 2>/dev/null || echo "Container not found or already removed"
 
-          docker pull ${{ secrets.DOCKER_USERNAME }}/yaggugifrontapp:latest
+        docker pull ${{ secrets.DOCKER_USERNAME }}/yaggugifrontapp:latest
 
-          docker run -d -p 3000:3000 --name yaggugifrontapp ${{ secrets.DOCKER_USERNAME }}/yaggugifrontapp:latest
+        docker run -d -p 3000:3000 --name yaggugifrontapp ${{ secrets.DOCKER_USERNAME }}/yaggugifrontapp:latest
